# Generated by Django 4.2.8 on 2023-12-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messages_userprofile_stock_answer_delete_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
