# Generated by Django 4.2.8 on 2023-12-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_botpersonality_remove_userprofile_llm_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botpersonality',
            options={'verbose_name_plural': 'bot personalities'},
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'friends'},
        ),
        migrations.AddField(
            model_name='botpersonality',
            name='personality_type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
