# Generated by Django 4.2.8 on 2023-12-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_userprofile_personalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botpersonality',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='botpersonality',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
